clean: true
author: Joshua Emmons
author_url: https://figure.ink
github_url: https://github.com/jemmons/Gauntlet
module: Gauntlet
xcodebuild_arguments: 
  - '-project'
  - 'Support/Gauntlet.xcodeproj'
docset_path: docset  
custom_categories:
  - name: Public Interface
    children:
    - StateType
    - StateMachine
    - StateTransitionDelegates
